services:
  db:
    image: postgres:15
    platform: linux/amd64  
    container_name: library_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"

  app:
    build: .
    platform: linux/amd64  
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/library_db
    depends_on:
      - db